added message

diff --git a/ejaaba b/ejaaba
--- a/ejaaba
+++ b/ejaaba
@@ -55,4 +55,9 @@ case $1 in
 		curl -s -b ./ejaaba_cookies -c ./ejaaba_cookies -H 'X-CSRF-TOKEN: '`curl -L -s -b ./ejaaba_cookies -c ./ejaaba_cookies "https://ejaaba.com/ask" | grep -oP '(?<=csrf-token" content=")[^"]*'` -F 'file=@'$2 "https://ejaaba.com/upload" | sed 's/{"url":"\|\\\|"}//g' ||
 		echo 'Check the file'
 		;;
+	message)
+	    [[ "$2" == "" ]] && (echo 'No responder is specified' && exit 1) || to="$2"
+	    [[ "$3" == "" ]] && (echo 'No message is specified' && exit 1) ||  message="$3"
+	    curl -L -s -b ./ejaaba_cookies -c ./ejaaba_cookies -d "_token=`curl -s -b ./ejaaba_cookies -c ./ejaaba_cookies 'https://ejaaba.com/' | grep -oP '(?<=token" value=").[^"]*' | head -n1`" --data-urlencode "message=$message" 'https://ejaaba.com/create-conversation/'"$to" > /tmp/ejaaba_page; cat /tmp/ejaaba_page | grep "<div>محادثة مع <a href=\"https://ejaaba.com/u/${to}\">" && echo 'Sent' || echo 'Error'
+	    ;;
 esac;
